services:
  pihole:
    dns:
      - 1.1.1.1
      - 8.8.8.8
    image: pihole/pihole:latest
    container_name: pihole
    network_mode: "host"
    restart: unless-stopped
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      FTLCONF_webserver_api_password: ${PIHOLE_ADMIN_PASSWORD}
      FTLCONF_webserver_port: "8080o,[::]:8080o,8443os,[::]:8443os"
    volumes:
      - ./etc-pihole:/etc/pihole
