title: "Homelab"

defaultEnable: false

groups:
  - name: Infrastructure
    icon: mdi-server

services:
  - name: Nginx
    group: Infrastructure
    icon: mdi-web
    url: http://homelab-01
    description: Reverse Proxy / Web Server

  - name: Gitea
    group: Infrastructure
    icon: mdi-git
    url: http://homelab-01:3000
    description: Self-hosted Git service

  - name: Pi-hole
    group: Infrastructure
    icon: mdi-shield-check
    url: http://homelab-01:8080/admin
    description: Network-wide Ad Blocking
  
  - name: Portainer
    group: Infrastructure
    icon: mdi-docker
    url: http://homelab-01:9000
    description: Docker Management UI