- Applications:
    - Gitea:
        icon: gitea
        href: http://homelab-01:3000
        description: Self-hosted Git

    - Immich:
        icon: immich
        href: http://homelab-01:2283
        description: Photo & Video Backup

    - Homelab Github:
        icon: mdi-github
        href: https://github.com/loki3-coding/homelab-01
        description: Github repo

- Monitoring:
    - Grafana:
        icon: grafana
        href: http://homelab-01:3002
        description: Dashboards & Metrics

    - Prometheus:
        icon: prometheus
        href: http://homelab-01:9091
        description: Metrics Database

    - Loki:
        icon: loki
        href: http://homelab-01:3002/explore?orgId=1&left=%7B%22datasource%22:%22loki%22%7D
        description: Log Aggregation

- Infrastructure:
    - Portainer:
        icon: docker
        href: http://homelab-01:9000
        description: Docker UI

    - Pi-hole:
        icon: pi-hole
        href: http://homelab-01:8080/admin
        description: DNS & Adblock

    - pgAdmin:
        icon: pgadmin
        href: http://homelab-01:5050
        description: PostgreSQL Admin

    - Tailscale Admin:
        icon: mdi-vpn
        href: https://login.tailscale.com/admin/machines
        description: Network management
