- Applications:
    - Gitea:
        icon: gitea
        href: http://homelab-01:3000
        description: Self-hosted Git

    - Immich:
        icon: immich
        href: http://homelab-01:2283
        description: Photo & Video Backup

- Infrastructure:
    - Cockpit:
        icon: cockpit
        href: http://homelab-01:9090
        description: Server Management

    - Pi-hole:
        icon: pi-hole
        href: http://homelab-01:8080/admin
        description: DNS & Adblock

    - Portainer:
        icon: docker
        href: http://homelab-01:9000
        description: Docker UI

    - pgAdmin:
        icon: pgadmin
        href: http://homelab-01:5050
        description: PostgreSQL Admin
