- Applications:
    - Gitea:
        icon: gitea
        href: https://gitea.homelab.com
        description: Self-hosted Git

    - Immich:
        icon: immich
        href: https://immich.homelab.com
        description: Photo & Video Backup

    - Homelab Github:
        icon: mdi-github
        href: https://github.com/loki3-coding/homelab-01
        description: Github repo

- Monitoring:
    - Grafana:
        icon: grafana
        href: https://grafana.homelab.com
        description: Dashboards & Metrics

    - Prometheus:
        icon: prometheus
        href: https://prometheus.homelab.com
        description: Metrics Database

    - Loki:
        icon: loki
        href: https://grafana.homelab.com/explore?orgId=1&left=%7B%22datasource%22:%22loki%22%7D
        description: Log Aggregation

- Infrastructure:
    - Portainer:
        icon: docker
        href: https://portainer.homelab.com
        description: Docker UI

    - Pi-hole:
        icon: pi-hole
        href: https://pihole.homelab.com/admin
        description: DNS & Adblock

    - pgAdmin:
        icon: pgadmin
        href: http://homelab-01:5050
        description: PostgreSQL Admin (Manual Start)

    - Tailscale Admin:
        icon: mdi-vpn
        href: https://login.tailscale.com/admin/machines
        description: Network management
