- Infrastructure:
    - Cockpit:
        href: http://homelab-01:9090
        description: Server Management

    - Gitea:
        href: http://homelab-01:3000
        description: Self-hosted Git

    - Pi-hole:
        href: http://homelab-01:8080/admin
        description: DNS & Adblock

    - Portainer:
        href: http://homelab-01:9000
        description: Docker UI